# -*- coding: utf-8 -*-
"""Ion Thruster Validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsPjnV8LUjNvszV5H-1-ItQVUHhQQRDg
"""

import numpy as np
import matplotlib.pyplot as plt

angles = np.linspace(120, 180, 600)
openness = np.sin(np.radians(angles / 2))

val_160 = np.sin(np.radians(160 / 2))
val_180 = np.sin(np.radians(180 / 2))
remaining_gain = (val_180 - val_160) / val_180 * 100

fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(angles, openness, linewidth=2)
ax.axvline(160, linestyle='--', linewidth=1.5)
ax.set_xlabel("Collector Angle (degrees)")
ax.set_ylabel("Normalized Channel Openness")
ax.set_title("Geometric Plateau Model Based on Projected Channel Width")
ax.text(
    161,
    val_160 - 0.03,
    f"160°\nRemaining geometric gain ≈ {remaining_gain:.2f}%",
    fontsize=9
)
ax.grid(True, alpha=0.3)
ax.set_xlim(120, 180)
ax.set_ylim(0.84, 1.01)

plt.tight_layout()
plt.show()